### ISSUE TITLE
About “记得把qemu修改为bochs！！”

### ISSUE THREAD

**Issue by huanngzh** [huahuaxiaomuzhu/pintos-docker#3]
What does this mean? How to operate?

**Comment by huahuaxiaomuzhu** [comment]
这里指的是makefile里的那个simulator的选项，因为有些版本的源码用的是"--qemu"(?)
![image](https://user-images.githubusercontent.com/56588699/137338529-90b686c0-dbf0-40f5-9b00-960d0438bb4e.png)
进行如图所示替换即可
